### PR TITLE
adds cache entry point to strapi.middleware

### LINKED ISSUE #27: Bust cache from Models - Lifecycle hooks
I have a custom API which get's the data from different content types. The inbuilt mechanism doesn't automatically refreshes the cache on custom routes if the content type data is changed. As per documents `ctx` is required to bust the cache.

`await ctx.middleware.cache.bust({ model: 'posts' });`

But `ctx` is not available in models. How can I manually bust the cache from models life cycle hooks like beforeDelete

### PR DESCRIPTION
**Pull request by meck93**
Hello everyone, 

Since I have had a similar issue, I thought I would help out and implement the idea discussed in #27 (closes #27)
If you have any suggestions or would like to change/rename something let me know. 

Thanks for the great work @patrixr

### CODE REVIEW

**Review by patrixr — APPROVED** [review]
Hi @meck93 

Thanks for this ! Happy to merge this in as it's a non-intrusive change.

Could you bump the version in package.json, that will allow auto-publishing to NPM (I think 1.2.0)

Cheers !

**Comment by meck93** [comment]
@patrixr quick question. should I have a look at the dependencies and see if there are new versions available?

**Comment by patrixr** [comment]
> @patrixr quick question. should I have a look at the dependencies and see if there are new versions available? 

@meck93 We can probably do that separately. I'll merge this PR as it is

**Comment by meck93** [comment]
@patrixr sounds good to me. I'll have a look at the non-breaking dependency changes.

**Pull request merged**
