### PR TITLE
Add option to bypass serving cache entry

### PR DESCRIPTION
**Pull request by julesrenaud**
As mentioned in #34

### CODE REVIEW

**Comment by julesrenaud** [comment]
I went further and added an option to generate and cache the ETag (via the crypto module with md5) alongside ctx.body so it won't have to be hashed on all requests when trying to match the `If-None-Match` header.

I simply add `_etag` to the existing cache key and store it alongside the payload cache. It gets picked up by the existing regex when busting the cache.

**Comment by patrixr** [comment]
Hi @julesrenaud 

It looks to me that those changes, although useful in your context, don't really make sense from the perspective of a reusable npm package.

- The bypass cache option here results in disabling the main feature of this module altogether

- Storing the ETag here does not actually achieve anything since it's never read. I understand that you probably read it yourself, but I need to look at this as other users would.

Do let me know if I misunderstood anything, but I see these changes as specific to your implementation, and therefore not appropriate for an npm package update. Hope you understand : )

I would recommend you create a local middleware in your project, feel free to grab any code from here to set it up.

**Comment by julesrenaud** [comment]
Hi @patrixr 

Using ETags is a standard practice for cache invalidation on the front end which is currently missing from Strapi but is quite important when envisioning building performant front-end apps consuming a REST API with a stable caching layer. I've done some ground work on that, but a caching layer is obviously important on the back end as you well know. I get that my additions encroach on the codebase but I assure you I’m following a standardized playbook for cache invalidation.

Would you consider creating a feature where it would be possible to hook in to the middleware and be able to manipulate the response (avoiding it in my use case) and the storing of cache entries? (adding more cache entries in my use case) I think that would widen the middleware’s appeal without rescoping it.

**Comment by patrixr** [comment]
Hi @julesrenaud 

I think hooking into the middleware is definitely preferable

We already have a `populateStrapiMiddleware` option which sets `strapi.middleware.cache` with a handful of useful functions

Maybe something like this would work:

```javascript
const { cache } = strapi.middleware;
const { store } = cache;

cache.on('entry', (model, cacheKey, body)=> {
   store.set(`${cacheKey}_etag`, ...);
});
```

I would also be happy to modify the core of the middleware itself if the cache invalidation was added as well, storing the etag is just weird without the context of your implementation

**Comment by julesrenaud** [comment]
Hi @patrixr 

I'm currently using `strapi.middleware.cache` to read the cache entries in my cache invalidation logic, very useful! It would make sense to add a hook there for sure I think.

> I would also be happy to modify the core of the middleware itself if cache invalidation features were added as well (304s, etc, ...) to make it a more rounded and useful feature, storing the etag is just weird without the context of your implementation

That would be great! I think it would enhance this already-great middleware and would be much better than my current course of action. If you don't I'll go ahead and start implementing this in a separate pull request. Saving on body size alone (without cache) doesn't make much sense anyways, so baking it in the middleware seem like a good idea!

**Comment by patrixr** [comment]
@julesrenaud That would be an _amazing_ addition ! It's been on my mind for a while but haven't found the time/energy to get to it. Many thanks !

I think it could be enabled with an option such as `enableEtagSupport: true`

**Comment by julesrenaud** [comment]
@patrixr I'll get right on that :)

**Pull request closed without merging**
