### PR TITLE
feat: add redis cluster option

### PR DESCRIPTION
**Pull request by brunosilvafreitas**
It enables users to use Redis Cluster mode

### CODE REVIEW

**Comment by patrixr** [comment]
Hi @brunosilvafreitas, 

I have no issue merging this. Could you bump the minor version in package.json ? (for the auto publishes to npm)

However do note that this project has been deprecated in favor of [strapi-community/strapi-plugin-rest-cache](https://github.com/strapi-community/strapi-plugin-rest-cache), so I'd recommend you migrate over and possibly contribute to that project instead.

**Comment by brunosilvafreitas** [comment]
Hi @patrixr! I changed the version now!

Of course, we are working on migrating Strapi version 3 to 4, but this will take a while and we really need to implement caching first...

Thank you, your project will help us a lot!

**Comment by patrixr** [comment]
No worries, I'll merge this :)

**Comment by patrixr** [comment]
@brunosilvafreitas Your changes are now available on npm

**Pull request merged**
